### ISSUE TITLE
rudderstack isn't sending data to bigquery

### ISSUE THREAD

**Issue by ivan006** [rudderlabs/rudder-server#1079]
our data plane is https://onecustomffp.dataplane.rudderstack.com  

we set up a opensource self hosted docker rudder server and we set up a source which is recieving fine and a destination on BigQuery but our destination warehouse is completely empty (however our google "bucket" is being populated) any thoughts? thanks

**Comment by psrikanth88** [comment]
@ivan006 can you check the sync status on the dashboard https://app.rudderstack.com/syncs Make sure you are running one of the latest versions of server for the dashboard to be available eg. [rudderlabs/rudder-server:14062021.222504](https://hub.docker.com/layers/rudderlabs/rudder-server/14062021.222504/images/sha256-2316739d9d909f4f86ada167289be44ddc4bbc61b597901edd40b31fb33be1f2?context=explore)

Other alternative is to check on the "Live Events" in destination page
