### ISSUE TITLE
Some syncs got aborted with `pq: relation ... does not exist` errors, retrying did not help

### ISSUE THREAD

**Issue by morl-la** [rudderlabs/rudder-server#1235]
**Describe the bug**
Some syncs got aborted with `pq: relation ... does not exist` errors similar to the one below:
`pq: relation "rudder_staging_identifies_68876e4608444cbaab17f24fc6962a70" does not exist'`

On some syncs, `Retry Now` solved it. On others, even 10 retries did not help and all failed with the same errors.
One thing to note is on every retry the relation name was different.

**Steps to reproduce the bug**
N/A - just had many aborted syncs on my account

**Expected behavior**
Not seeing `pg: relation ... does not exist` errors on syncs. This is not the first time we've encountered this.
Not getting aborted syncs.

**Screenshots**
This is the only screenshot I have. while it does not show the actual error - it shows 2 rows failing on that error and another (users) which got stuck and no matter how many retries I did it kept stuck at `sync in progress`
![image](https://user-images.githubusercontent.com/44611568/133105275-364cc207-d853-4c8a-9c15-562e40c0bd08.png)

**Desktop (please complete the following information):**
Irrelevant - this is a problem with managed service.

**Smartphone (please complete the following information):**
Irrelevant - this is a problem with managed service.

**Any additional context**
I have spoken with @psrikanth88 on the support channel - he is familiar with it and helped rerun all of our aborted syncs using internal tools.
On another note: it would be handy to have a "retry all" button on all aborted syncs - I had 200+ aborted syncs and it's not fun retrying them one by one...

Thanks,
Mor from Zira.

**Comment by dhawal1248** [comment]
Hey @morl-la , we have added a [fix](https://github.com/rudderlabs/rudder-server/pull/1228) for this.
We checked your destination - all syncs are going through fine.
Closing the issue.
