### ISSUE TITLE
Include Observability stack in docker-compose

### ISSUE THREAD

**Issue by psrikanth88** [rudderlabs/rudder-server#1340]
RudderStack emits application metrics in `statsd` format over port 8125. The metrics can be captured by a telegraf server and persisted in InfluxDB timescale database. Grafana could be used to visualize data in InfluxDB

Including these components in docker-compose can enable users running RudderStack to have an end to end view of the application performance. Dashboards to include with Grafana setup can be also publicly shared on https://grafana.com/grafana/dashboards/

References:

- To run similar components using docker https://github.com/samuelebistoletti/docker-statsd-influxdb-grafana
- Example architecture running in k8s
![RudderStack2x_(81)](https://user-images.githubusercontent.com/8225792/137571638-1f896b12-2e8b-463c-8cc0-0b7b5081ccce.png)

**Comment by chandumlg** [comment]
We now have a `metrics-exporter` in docker-compose. If needed, users can have prometheus scrape metrics from this.
