### ISSUE TITLE
Support env var for sslmode=require at jobsdb.go

### ISSUE THREAD

**Issue by deeweey** [rudderlabs/rudder-server#151]
Hi,

I wanted to give rudder a try with our hosted postgres db (via DigitalOcean) and we need to connect with [sslmode=require](https://pkg.go.dev/github.com/lib/pq?tab=doc). Currently it is hardcoded to disable at [jobsdb.go](https://github.com/rudderlabs/rudder-server/blob/48bc9e49415ab1f0775fcc2d723f4b89a98db1f6/jobsdb/jobsdb.go#L265)

Would it be an idea to support JOBS_DB_SSLMODE and default it to disable?

**Comment by SumanthPuram** [comment]
Sure, we need to add support. As you have already seen jobsdb.go, this would be a simple change. Do you want to submit a pull request for this? @deeweey
