### ISSUE TITLE
Compatible with Cockroachdb?

### ISSUE THREAD

**Issue by fire** [rudderlabs/rudder-server#163]
Has anyone tried?

The usual thing that breaks with postgresql compatibility is triggers.

**Comment by SumanthPuram** [comment]
We haven't tested so far with Cockroachdb. It should work if the only difference is triggers.

But we have a couple of features on the pipeline that are going to use Postgres triggers.

**Comment by SumanthPuram** [comment]
@fire Hope that answered your question. I will close this issue unless you want more information.

**Comment by fire** [comment]
Thanks.

**Comment by fire** [comment]
I assume that rudder's roadmap is to break cockroachdb compatibility after the new features land.

**Comment by SumanthPuram** [comment]
Cockroachdb compatibility is not in the roadmap right now. Is there any particular reason why you want to use Cockroachdb with Rudder?

**Comment by ramkumarkb** [comment]
@SumanthPuram - Kindly consider not breaking CockroachDB compatibility. IMHO, the scale out property of CrDB would really be interesting for scaling out Rudderstack itself. Also deploying CrDB on non-docker environments (it is just like Rudderstack go binary) is far simpler and DevOps friendly.
