### ISSUE TITLE
there is no utils/config-gen directory 

### ISSUE THREAD

**Issue by smcnally** [rudderlabs/rudder-server#166]
README notes to install and start config-gen. There is no such directory. 
https://github.com/rudderlabs/rudder-server/blob/master/README.md#setup

>     Checkout the config-gen git checkout -b config-gen
>     cd utils/config-gen
>     npm install
>     npm start

**Comment by soumyadebm** [comment]
Missed the step of git pull
git checkout -b config-gen
git pull origin config-gen

Updated the README now. We will also merge the branches

**Comment by SumanthPuram** [comment]
The changes are merged into master. Can you please check if you still face the issue? @smcnally

**Comment by SumanthPuram** [comment]
This is merged to master.
