### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by smcnally** [rudderlabs/rudder-server#167]
Using the Docker setup instructions here: 
https://github.com/rudderlabs/rudder-server#setup-instructions-docker

`docker-compose up --build `

throws this error

> ERROR: Version in "./docker-compose.yml" is unsupported.

for me with docker-compose version 1.17.1

changing the version from "3.7" to "3" in 

`rudder-server/build/docker-compose.yml`

allows the build process to continue.

**Comment by SanketDG** [comment]
Looks like specifying a more "loose" version helps here to be compatible with docker versions[0]

[0]: https://docs.docker.com/compose/compose-file/compose-versioning/

**Comment by sigismund** [comment]
If I am not mistaken docker-compose 1.17.1 doesn't support 3.7 syntax. This is mostly likely reason for your error.
Using single digit version could lead to new problems, where users will try to use features which aren't supported by docker engine.
