### ISSUE TITLE
Metrics missing

### ISSUE THREAD

**Issue by azhelev** [rudderlabs/rudder-server#1672]
**Describe the bug**
Some metrics are not available. By not available i mean they are not emitted at all. Most importantly `recovery.mode_normal` is not there. If i restart the server several times or crash it the metric may appear.
Several other metrics are also behaving strangely. `jobsdb.gw_tables_count`, `jobsdb.tables_count`, `jobsdb.batch_rt_tables_count` show a value initially but then they disappear.

![image](https://user-images.githubusercontent.com/12055675/154448384-ad38ecde-8a35-4a79-b762-f121007134ae.png)

**Steps to reproduce the bug**
1. Start rudder-server

**Expected behavior**
All metrics are emitted and available

**Any additional context**
Running self-hosted rudderstack on kubernetes, installed with the helm chart. Metrics are obtained by the telegraf sidecar container.

**Comment by chandumlg** [comment]
@azhelev Table count metrics are emitted whenever a new dataset is created. If there is not activity (meaning no flow of events and no new datasets are created), metrics are emitted. Run some load and check.

`recovery.mode_normal` is a gauge type metric, which is fired every 10s. It works for me. Can you double check?

Thank you for your interest.

**Comment by azhelev** [comment]
@chandumlg thanks for the clarification the table count metrics, that explains a lot.
I'm sure about the `recovery.mode_normal` metric, see the following screenshot.

![image](https://user-images.githubusercontent.com/12055675/154480653-606035e6-1886-43d6-8868-ce08f9c6f1cc.png)

Here i intentionally crashed the rudder-server process (exec into the pod and kill the pid). After the container came back up the metric showed up and is emitted regularly as it should along with some other metrics that were not present.
Notice how gateway requests and number of events metrics are present all the time.
![image](https://user-images.githubusercontent.com/12055675/154481024-7fb31a63-9dc4-430b-88ff-b28d90a7da58.png)

Regards
Atanas

**Comment by chandumlg** [comment]
@saurav-malani Can you take a look at this pls.

**Comment by saurav-malani** [comment]
@azhelev we managed to replicate the issue. Also, we have identified, the reason behind why we are not getting the metrics. Essentially, it is related to the ordering of `telegraf_sidecar` & `backend` containers. We are working on fixing it. 
Thanks for bringing this to our notice.

**Comment by saurav-malani** [comment]
@azhelev we have fixed the issue. Thanks for pointing it out.
