### ISSUE TITLE
I want to be able to disable the auto-generated `view` from Rudderstack

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [rudderlabs/rudder-server#1806]
### Problem
We've been using Rudderstack for a while at Lightdash and it's great :)

But, the auto-generated `view` files that Rudderstack adds to BigQuery are causing us two problems:

1.  **Using Google Bigquery [Wildcard Selection](https://cloud.google.com/bigquery/docs/querying-wildcard-tables).**
  This command requires that there [aren't any views in the list of tables you're selecting. ](https://cloud.google.com/bigquery/docs/querying-wildcard-tables#:~:text=The%20wildcard%20table%20functionality%20does%20not%20support%20views.%20If%20the%20wildcard%20table%20matches%20any%20view%20in%20the%20dataset%2C%20the%20query%20returns%20an%20error.%20This%20is%20true%20whether%20or%20not%20your%20query%20contains%20a%20WHERE%20clause%20on%20the%20_TABLE_SUFFIX%20pseudo%20column%20to%20filter%20out%20the%20view.). Wildcard selection is really important for being able to build a table that looks at **_all_** of our Rudderstack event data (instead of having to list out all of the tables + update the `UNION ALL` each time we add a new event).

2. **We can't actually use the auto-generated `view` files (because they're filtered to only include data from the past 60 days.)**
  I actually end up re-generating the view files and renaming them because the views are filtered to only include data from the past 60 days and we can't find a way to change this. So, the view files are now just taking up space and adding confusion because there are two view files for each event table in our data warehouse. 

^[Reading through the docs](https://www.rudderstack.com/docs/data-warehouse-integrations/google-bigquery/), I can't find any reference to updating the view tables being possible. I'm wondering if there are settings to these that I can't find? 

### Potential solution
The first problem above is more critical than the second one, so either being able to:
1. change the name of the views so that they're _**prefixed**_ with `view_` instead of having `_view` as a suffix. 
2. having the option in the project settings to turn off auto-generated views. 

^The second option solves both the problems above, but you might have a better solution than either of these! 😊

**Comment by chandumlg** [comment]
Thanks @TuringLovesDeathMetal for raising the issue.

@sivashanmukh Can you guys please address this.

**Comment by Jayachand** [comment]
@TuringLovesDeathMetal 
Views are created for each table to give privilege to customer of viewing data of past 60 days without duplicate entries. This was done before Bigquery supported upserts. 

With latest release, deduplication of events is enabled and there would be no advantage from the views. You can delete views for created tables if they are not required as they are not necessary for you. Although we still create views for newly created tables as of now. And we would stop doing this in our next release. Until then, feel free to remove any views that you don't need.

**Comment by TuringLovesDeathMetal** [comment]
Wow, amazing! Thanks so much @Jayachand - I'm going to close this assuming that it's solved in the next release. 

Also, really excited to remove all of the CTEs for deduplicating everything 😍
