### ISSUE TITLE
Removal of security specific key-values from the ruddestack GET Response

### ISSUE THREAD

**Issue by Kannaj** [rudderlabs/rudder-server#2075]
Hi,

As discussed over the slack group - the rudderstack GET request sends a response like the below

```json
{"appType": "EMBEDDED", "server":"UP", "db":"UP","acceptingEvents":"TRUE","routingEvents":"TRUE","mode":"NORMAL","goroutines":"636", "backendConfigMode": "API", "lastSync":"2022-06-18T14:58:11Z", "lastRegulationSync":""}
```

It would be best to remove keys like `goroutines` etc from the standard response

**Comment by chandumlg** [comment]
Fixed [here](https://github.com/rudderlabs/rudder-server/pull/2079)
