### ISSUE TITLE
Data plane Kubernetes deployment.

### ISSUE THREAD

**Issue by JoanMora** [rudderlabs/rudder-server#2113]
**Describe the bug**
Data plane crash reports.

**Steps to reproduce the bug**
Deploy the data plane on Kubernetes. 

**Any additional context**
See the logs attached.

[rudderstack_server_logs_before_crash.txt](https://github.com/rudderlabs/rudder-server/files/8991710/rudderstack_server_logs_before_crash.txt)

**Comment by cisse21** [comment]
Can you check if you have used the right workspace token for your deployment?

**Comment by chandumlg** [comment]
As @cisse21 mentioned, please try with the correct workspace token. 

Closing this for now. Feel free to open it in case it doesn't solve your problem.
