### ISSUE TITLE
Getting 301 redirect to `/debug/pprof` for hosted deployments

### ISSUE THREAD

**Issue by owlas** [rudderlabs/rudder-server#2155]
**Describe the bug**

I've just upgraded my rudderstack deployment and when I access any route I get this response and I'm redirected to `/debug/pprof`

```
curl -i https://my-rudderstack-deployment 
HTTP/2 301 
date: Mon, 11 Jul 2022 10:12:43 GMT
content-type: text/html; charset=utf-8
location: /debug/pprof/
```

This is a completely fresh deployment. I can't reproduce it with `docker-compose` - I thought this might be a problem with my infrastructure, but I don't know why it would redirect to `/debug/pprof`

I also don't think `/debug/pprof` should be available in production since it could contain sensitive information.

**Steps to reproduce the bug**

So far I have only reproduced this with render.com:

1. Go to this repo: https://github.com/lightdash/rudderstack
2. Click deploy to render
3. Once it's deployed, run `curl localhost:8080` in the container - works fine
4. Now run curl against the external domain name `rudderstack.onrender.com` - gives `301 ->/debug/pprof`

**Expected behavior**
It should not redirect requests. It should never show `/debug/pprof` in production

**Screenshots**
Not sure if this helps but inside the container (this is in Kubernetes under the hood) I can successfully check `localhost` but not with the cluster endpoint for the exact same service, why would that be?

<img width="1012" alt="Screenshot 2022-07-11 at 11 19 08" src="https://user-images.githubusercontent.com/11660098/178243310-c7f449c3-ed0b-4ae0-875e-753608d109b3.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Any additional context**
Add any other context that will help us understand the problem better.

**Comment by lvrach** [comment]
Hello @owlas, 

Thanks for the detailed report.

rudder-server is using multiple endpoints for different purposes:
* web - runs by default at `8080`, it is meant to be publicly exposed and expose our event streaming API
* admin - runs by default at `8089`, should be privately used for administrative tasks
* debug - runs by default at `7777`, exposes [pprof](https://pkg.go.dev/net/http/pprof) endpoints and should remain private as well.

In your case, it seems `rudderstack.onrender.com` is mapped to `7777`. I am trying to investigate why, I haven't used render.com before, but in your yaml file there is no mention of the port you want to expose. 

If a service exposes multiple ports, how does render.com determines which one to use? Maybe they opt to use the smaller one 🤔 

I will try to replicate/reproduce the issue and understand more about how render.com works.

**Comment by owlas** [comment]
Ahhh!!! Thanks so much, I can make sure that `8080` is only exposed publicly. 

So sorry! Although it would be useful in the docs to know about those endpoints. 

Thanks so much @lvrach - I was quite worried when I could see `/debug/pprof`

I think this issue is closed

**Comment by owlas** [comment]
In case anybody else wants to try this with render, I've updated our template. The problem was the automatic port detection: https://github.com/lightdash/rudderstack
