### ISSUE TITLE
Dead letter queue

### ISSUE THREAD

**Issue by cvlendistry** [rudderlabs/rudder-server#2393]
When there is a failure to deliver to the destination, there has to be an option to specify an S3 bucket to put the raw event that failed so that a background process can investigate / backfill the failed events.

**Comment by chandumlg** [comment]
We already have an option to upload the aborted events to S3 now.

The supported object storages & the environment variables to be provided can be found here.
https://github.com/rudderlabs/rudder-server/blob/097c61bafd041a87060da4ec27ecb39c8efa94ec/services/filemanager/filemanager.go#L91

**Comment by chandumlg** [comment]
Closing this issue. Feel free to reopen it in case of any issues.
