### ISSUE TITLE
Rudder as a datasource for Tableau?

### ISSUE THREAD

**Issue by henricook** [rudderlabs/rudder-server#248]
Hi Rudder team,

I've got a tableau install on-prem, i'm looking for an event processing service that will bucket events sent from my app and then be able to present the bucketed/transformed data to Tableau as a data source. Is Rudder a good fit for this?

**Comment by mindhash** [comment]
@henricook I have just started exploring rudderstack but I dont think it will achieve all of what you are looking for.  This is more of connector than storage. 
so you could 
- Send events from your app to rudder stack. 
- Setup Redshift / Snowflake as destination
- Connect Tableau to the dw  (redshift/snowflake)
Will also recommend using DBT (getdbt.com)

Hope this helps.

**Comment by henricook** [comment]
Ah I'd missed that @mindhash thank you, I thought Rudder also handled persistence.

Thanks for taking the time
