### ISSUE TITLE
Following Setup Instructions for Docker Causes a Crash of the Backend

### ISSUE THREAD

**Issue by jpfifer** [rudderlabs/rudder-server#256]
Following the [Docker Setup Instructions](https://github.com/rudderlabs/rudder-server#setup-instructions-docker) will produce a docker image for backend that will crash due to `sql.NullTime` not existing. 

It looks like `sql.NullTime` was added in golang 1.13, but the [`build/Dockerfile-dev`](https://github.com/rudderlabs/rudder-server/blob/master/build/Dockerfile-dev) is using golang 1.12. 

I was able to get the backend to run by switching the base image to `golang:1.14-alpine` in `build/Dockerfile-dev`. It does get it running on my local machine, but don't know if everything is fine with a newer version of golang.

**Comment by SumanthPuram** [comment]
Thanks for reporting, the fix has been tested and merged.
