### ISSUE TITLE
[Improvement] CockroachDB drivers

### ISSUE THREAD

**Issue by rwrz** [rudderlabs/rudder-server#2692]
I'm using Rudderstack in a k8s environment, which is working great.
But, I think would be a "low hanging fruit" to achieve compatibility with CockroachDB, since it uses the same drivers as PostgreSQL.
I've tried, but some of the DB migration queries didn't work out and then I was scared to keep "fixing" and after the initial work, it keeps erroring without noticing it (turning into a much bigger initiative than I initially planned).

Well, my point is, I'm happy to send a PR adding this support, but can someone from the team help me out pointing possible points of failure where we execute DB queries/commands and can possibly break. It would help a lot.

Also, any plans to improve the DB integration? It seems very coupled to PostgreSQL right now, it would help other issues like (#694) to succeed.

**Comment by atzoum** [comment]
Hi @rwrz, thank you very much for your interest and willingness to contribute to rudder server! We would be happy to accept a contribution from you, however please bear in mind that:
- Supporting multiple different database technologies is currently not in our roadmap. What we are trying to do now is to optimize rudder server's performance by benchmarking against PostgreSQL and taking advantage of any available feature this database has to offer.
- Supporting any other database than PostgreSQL would require us to run our test suite twice against both databases. Additionally, any CockroachDB incompatibility with PostgreSQL's existing or upcoming features would be a limiting factor that could hinder the future evolution of rudder server. For instance, CockroachDB doesn't seem to support LISTEN/NOTIFY commands, that is a feature we are already using.

If however adding support for CockroachDB proves to be straightforward and can be done with minimal changes and without affecting our current integration with PostgreSQL, we would be more than interested to accept your contribution! For reference, the `jobsdb` and `warehouse` packages contain the majority of code interacting with the database. Finally, under the `sql/migrations` folder you may find database schema migration files that take care of upgrading the database's schema to the latest version.

Thank you once more for your interest in rudder server!

**Comment by rwrz** [comment]
Thanks. I will close this issue.
Doesn't seems something possible right now.
