### ISSUE TITLE
Events not flowing to GA4 dashboard even after shown as successful on live events tab on destination

### ISSUE THREAD

**Issue by abhimez** [rudderlabs/rudder-server#2824]
**Describe the bug**
I am using self hosted rudderstack data plane, with GA4 firebase and s3 destinations. My events are flowing to s3 destination just fine but I am not seeing any events on GA4 dashboard. There is no error on GA4 destination events tab, all events are succeeding there as well. Changing the data plane url to rudderstack hosted one fixes the issue, the events start flowing to GA4 after that.

**Steps to reproduce the bug**

Use docker-compose setup for setting up self hosted data plane and add GA4 firebase destination.
Send any custom events to dataplane url. 
You wont see those events on GA4 dashboard even after shown as successful on live events tab of GA4 destination.

**Expected behavior**
Events should have flown to GA4.

**Comment by abhimez** [comment]
Got it working with some changes on Dockerfile and docker-compose.yml file.

**Comment by coolbaluk** [comment]
@abhimez I'm running into a similar issue, where sending an HTTP request to GA4 directly shows the event, but going through rudderstack doesn't work with the same data.

Can you go into what changes worked for you?

Thanks.

**Comment by abhimez** [comment]
please refer to this PR: https://github.com/rudderlabs/rudder-server/pull/2827
It has all the changes done to enable this.

**Comment by coolbaluk** [comment]
Thanks, can confirm that this change specifically makes it work:

`GA4:
    transformerProxy: true`
