### ISSUE TITLE
New versions of a transformation are not applied to the existing destination

### ISSUE THREAD

**Issue by tsrancsik** [rudderlabs/rudder-server#2890]
source: .Net
destination: Amplitude
RudderStack cloud
free plan
JavaScript transformation

I recognized that saving new versions of the transformation function is not applied to the existing destination. Removing and adding the transformation to the destination again solved the problem.

sample event:
```
{
    "anonymousId": null,
    "context": {
        "library": {
            "name": "RudderAnalytics.NET",
            "version": "1.0.1"
        }
    },
    "event": "AutoTrace.Performed",
    "integrations": {},
    "messageId": "b24d5eb8-ecef-42d1-84a1-497c11082ecc",
    "properties": {
        "source": "quickMenu"
    },
    "rudderId": "1703da0d-2472-459c-9bf0-4e7b66b4673a",
    "timestamp": "2023-01-20T11:26:09.8002130Z",
    "type": "track",
    "userId": "12345"
}
```

transformation:
```
export function transformEvent(event, metadata) {
    const eventNames = ["AutoTrace.Performed"];
    const eventName = event.event;
    const eventSources = ["inspector"];
    const eventSource = event.properties?.source;
    
    if (eventName && eventNames.includes(eventName) && eventSource && eventSources.includes(eventSource)) 
        return event;
}
```

**Comment by gitcommitshow** [comment]
Hi @tsrancsik , sorry I missed to comment on this earlier. I see that you have resolved the issue by removing and adding the transformation again to the the destination. So I will close this issue for now. If you have any additional comments, feel free to add in this issue. Thank you for posting this issue.
