### ISSUE TITLE
High memory consumption in version 1.5.5 leads to instances being killed

### ISSUE THREAD

**Issue by saques** [rudderlabs/rudder-server#2963]
**Context**:

We have been continuously running 2 ECS Fargate clusters, one with 3 tasks (let's call it A) and another one with 2 tasks (B) of the `rudder-server` and `rudder-transformer` bundle since early December with no major hiccups.

Our task definition was set to always pull the latest version of `rudder-server` from docker as in `rudderlabs/rudder-server:latest`

**Issue**:

Yesterday (Feb 8 2023), due to an unknown cause, one of the tasks on cluster A restarted. The other two instances kept running normally. Since then, ECS repeatedly kept shutting down and restarting _that specific instance_ due to it running out of memory. In the meantime, cluster B ran normally. The following chart shows the memory consumption of cluster A (note the sudden spike):

<img width="519" alt="Screenshot 2023-02-09 at 12 36 44" src="https://user-images.githubusercontent.com/15107944/217863566-3f27a0a6-6494-4342-b1a4-69fe934aa495.png">

Today morning (Feb 9 2023), in an effort to see if we could force all instances to return to normal levels of memory consumption, we moved forward and restarted both clusters A and B. And cluster B, which was up to that point running normally, began showing the same pattern as cluster A.

Suspecting that the version of `rudder-server` was at fault, we fixed the version to `1.4.5` (mid-December 2022), restarted both clusters, and went back to normal.

**Comment by cisse21** [comment]
Hey @saques 

we have 1.5.2 running on our production. Can you verify if that works without any memory spikes?

**Comment by atzoum** [comment]
Hey @saques, all releases between `1.5.0`-`1.5.5` use by default a problematic throttling implementation based on `go-rate`. In our production environments we are using a different algorithm, namely `CGRA`.
We just released `1.5.6` which now uses the `GCRA` algorithm by default. The problematic algorithm is being entirely removed in the upcoming release `1.6.0`.
Even though we didn't experience any memory-related issues in the short period that we used the problematic algorithm in production, please let us know if `1.5.6` addresses your issues.

**Comment by saques** [comment]
Hi @atzoum, thanks for your detailed answer.
I was able to verify that version `1.5.6` has a more consistent memory profile.
I'm closing this issue now. Thanks for your help!
