### ISSUE TITLE
Singular integration is not working

### ISSUE THREAD

**Issue by vladaman** [rudderlabs/rudder-server#3045]
As per discussion with Singular, the Rudderstack integration is not working. Events are not being delivered.

**Comment by Gauravudia** [comment]
> As per discussion with Singular, the Rudderstack integration is not working. Events are not being delivered.

@vladaman Are you using Cloud mode to send the events through Rudderstack?

**Comment by vladaman** [comment]
Yes, we use both Cloud Rudderstack and Cloud Singular.

**Comment by Gauravudia** [comment]
Hi, @vladaman We are able to successfully send the events to the `Singular` destination using RudderStack cloud mode integration. Please re-check the destination configuration once. If the issue still persists you can share your configuration on RudderStack open-source [channel](https://rudderstack.slack.com/archives/C01E4PLB135)

**Comment by gitcommitshow** [comment]
I will close this issue as it seems to be fixed. Feel free to reopen the issue if not fixed yet.
