### ISSUE TITLE
The latest version has a lot of error logs about adaptive_payload_limiter

### ISSUE THREAD

**Issue by KqLLL** [rudderlabs/rudder-server#3046]
**Describe the bug**
The latest version has a lot of error logs about adaptive_payload_limiter

```[inputs.statsd] Error: parsing value to float64: adaptive_payload_limiter_state,instanceName=rudderstack-1,namespace=rudderstack:|g```
![image](https://user-images.githubusercontent.com/76542414/221794941-d064b791-28ba-4985-bba4-1026f4380b67.png)

**Steps to reproduce the bug**
Enter the steps to reproduce the behavior. 

For e.g:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Any additional context**
Add any other context that will help us understand the problem better.

**Comment by cisse21** [comment]
@KqLLL Thanks for reporting, we are looking into it now. We will get back to you in case we need any more details

**Comment by atzoum** [comment]
Hey @KqLLL, this is now fixed in the latest rudder-server release `1.6.2`
