### ISSUE TITLE
Gzip Option not working in Self-Hosted Data Plane with Python SDK

### ISSUE THREAD

**Issue by keenborder786** [rudderlabs/rudder-server#3181]
**Describe the bug**

I am using the RudderStack Python SDK to send data to S3 Data-Lake(Warehouse destination). However, despite configuring the gzip attribute to be false. The final JSON files are being uploaded as zipped on the stagging logs folder

**Steps to reproduce the bug**
Following is my simple python script which I am using for dev purposes to test the SDK:

```python
from country_list import countries_for_language
import rudderstack.analytics as rudder_analytics
import random
import uuid
import time
import secrets

WRITE_KEY = ''
DATA_PLANE_URL = 'http://127.0.0.1:8080'

rudder_analytics.write_key = WRITE_KEY
rudder_analytics.dataPlaneUrl = DATA_PLANE_URL
rudder_analytics.gzip = False

rudder_analytics.identify(
"2121",
{
    "email": "{secret_token}@gmail.com",
    "first_name": "secret_token",
    "last_name": 'secret_token'+'last_name',
    "age": "age",
},
{"context": {
    "ip":  "111.XXX.XXX"
    }
})
```

You can clearly see the gzip is set to false. However,  the logs are still being uploaded as zipped on my stagging folder:

![image](https://user-images.githubusercontent.com/45242107/230661829-4fdc2a80-477b-4a88-a6fd-78f6d3c923e9.png)

**Expected behavior**
The expected behaviour as per the official documentation is that if gzip is set to be false then json should be uploaded as raw jsons and not as zipped jsons.

**Additional Context**

To provide some more context, I am using self-hosted Data-Plane Deployed on Kubernetes using helm. And I am using workSpaceConfig.json generated from Open-Source Control Plane to start my pipeline.

**Desktop Version**

- PRETTY_NAME="Ubuntu 22.04.1 LTS"
- NAME="Ubuntu"
- VERSION_ID="22.04"
- VERSION="22.04.1 LTS (Jammy Jellyfish)"
- VERSION_CODENAME=jammy
- ID=ubuntu
- ID_LIKE=debian
- HOME_URL="https://www.ubuntu.com/"
- SUPPORT_URL="https://help.ubuntu.com/"
- BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
- PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
- UBUNTU_CODENAME=jammy

**Tools Versions**

-     rudder-sdk-python 2.0.2
-     Python v3.9.1.5

**Helm Chart Version**
```console
 version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}
 ```

**Kubernetes Versions**
```console
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-18T02:16:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

**minikube Version**
- v1.28.0

**Comment by desusai7** [comment]
Hey @keenborder786 , 

The gzip configuration only applies to the request payloads being sent to the data plane, and the data plane would automatically decompress it. 

However, the staging files you are looking at are something different and you can refer more about it [here](https://www.rudderstack.com/docs/destinations/warehouse-destinations/faq/#what-is-the-file-storage-format-for-staging-and-load-files-in-different-object-storage-platforms)
