### ISSUE TITLE
BigQuery Warehouse - DataSet Location

### ISSUE THREAD

**Issue by WFrancois** [rudderlabs/rudder-server#357]
Hi !

I started using the rudder server locally but when adding the BigQuery destination I noticed that the "Location" configuration isn't being used ? (My DataSet is always created in the US)

When looking at the code I noticed that this location configuration wasn't used ? I've made a fix to create the Dataset with the correct location using this configuration so I could open a pull request with this change ?

Thanks :)

**Comment by psrikanth88** [comment]
@WFrancois Thanks for pointing out the bug. It would be great if you can raise a PR fixing this
