### ISSUE TITLE
invalid write key error

### ISSUE THREAD

**Issue by esmaeilram** [rudderlabs/rudder-server#3804]
i want to use opensource dashboard to host my dashboard.
i generated workspace.json from the opensource dashboard [link](https://github.com/rudderlabs/config-generator), I added it to rudderstack and it's imported properly in rudder-stack backend pod but I still get an invalid write-key error when I send a post request to my data plane.
webhook post
http://dataplane-url/v1/webhook?writeKey=$writekey
{
"stage": {
"user_transform": true,
"dest_transform": true,
"send_to_destination": true
},
"message": {
// RudderStack HTTP Payload (identify, track, etc.)
}
}
ps
My webhook post is working in rudderstack dashboard cloud but I want to host the opensource dashboard
response is :
<img width="946" alt="image" src="https://github.com/rudderlabs/rudder-server/assets/88314205/b2df50b1-702e-4c73-81ca-606330f2c19a">
![image](https://github.com/rudderlabs/rudder-server/assets/88314205/3d50b9ad-2110-47d3-a947-38bfc251f481)

any help?

**Comment by gitcommitshow** [comment]
@esmaeilram config-generator is deprecated. please use [RudderStack Cloud Control Plane](http://app.rudderstack.com/signup?type=opensource) instead.

**Comment by gitcommitshow** [comment]
I will close this issue as of now but feel free to reopen if you have more questions or context to share.
Also I recommend you to use [RudderStack Slack Community](https://www.rudderstack.com/join-rudderstack-slack-community/) for faster responses to your queries
