### ISSUE TITLE
Add UUID to Clickhouse table definition for zookeeper path

### ISSUE THREAD

**Issue by redsquare** [rudderlabs/rudder-server#4060]
https://github.com/rudderlabs/rudder-server/blob/6d2db454218ac53cd87b43c21fcfbedf37758e50/warehouse/integrations/clickhouse/clickhouse.go#L796C1-L796C83

Can we create clickhouse tables with the following, this avoids syn issues after dropping the table and Rudder not being able to recreate it - see https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/#q-i-cannot-reuse-zookeeper-path-after-dropping-the-table

CREATE ...
ON CLUSTER ...
ENGINE=ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}/', '{replica}')

**Comment by lvrach** [comment]
we use this link to track the issue internally https://linear.app/rudderstack/issue/PIPE-482/improve-clickhouse-add-uuid-for-zookeeper
