### ISSUE TITLE
S3 Replay Docs

### ISSUE THREAD

**Issue by eoghantelnyx** [rudderlabs/rudder-server#407]
I'm not sure how I can replay my S3 backups for new destinations? Is this something that we can create docs for?

**Comment by SumanthPuram** [comment]
@eoghantelnyx If you want to achieve this with open core, you can write a script to generate events following the RudderStack HTTP API spec. 
https://docs.rudderstack.com/rudderstack-api-spec/http-api-specification 

RudderStack enterprise version includes this feature.

**Comment by SumanthPuram** [comment]
If you can actually set this up for the community, that would be great.

for file in all_s3_files:
    read line
    use rudder_stack_sdk/HTTP API and make a request to the data plane
