### ISSUE TITLE
Rudderstack server reports massive 403 errors for Snowflake destination, but data is still uploaded to S3

### ISSUE THREAD

**Issue by KqLLL** [rudderlabs/rudder-server#4176]
**Describe the bug**
We follow [Snowflake Destinations](https://www.rudderstack.com/docs/destinations/warehouse-destinations/snowflake/) to set up the Snowflake destination and grant permissions to the Rudder server's AWS role so that it can work . But the logging system is getting a lot of error messages indicating that the AWS role is missing the "kms:GenerateDataKey" permission. Why?
**Steps to reproduce the bug**
Set up [Snowflake Destinations](https://www.rudderstack.com/docs/destinations/warehouse-destinations/snowflake/) on AWS EKS and it encrypts the objects using server-side encryption with either Amazon S3 managed keys (SSE-S3).
**Expected behavior** 
No error log exists
**Screenshots**
<img width="921" alt="image" src="https://github.com/rudderlabs/rudder-server/assets/76542414/42b476ac-f5ca-4d1f-9a62-9a400fdff2e9">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Any additional context**
Add any other context that will help us understand the problem better.

**Comment by cisse21** [comment]
We backup all the metadata related to warehouse uploads to S3 in order to avoid bloating the postgres tables and filling up the disk

**Comment by KqLLL** [comment]
> We backup all the metadata related to warehouse uploads to S3 in order to avoid bloating the postgres tables and filling up the disk

Why "kms:GenerateDataKey" permission is needed ?
