### ISSUE TITLE
Running rudder-server without a rudderstack account?

### ISSUE THREAD

**Issue by nbolten** [rudderlabs/rudder-server#428]
Hello there!

It's a bit counter-intuitive to me that self-hosting this application would require creating an account on the project's web page. I'm wondering whether is a method for running the rudder server without an account-based workspace token, or otherwise to know what the purpose of this token is. The docs don't really explain its purpose, but they all state that it's a required part of setup.

Keeping in mind that I haven't read the code yet nor do I have a specific example of a failure mode, the need for an externally-generated key makes me a bit apprehensive about placing potentially sensitive information through the system. Just to give an idea of where my concerns are coming from.

Thanks for any clarification!

**Comment by lokey** [comment]
You can use [RudderStack Config Generator](https://github.com/rudderlabs/rudder-server/wiki/RudderStack-Config-Generator) to generate config as a JSON and use it. The hosted control plane has some additional features like Live Event Debugger and Transformations so we generally recommend you use that.
