### ISSUE TITLE
Client IP in destination is incorrect

### ISSUE THREAD

**Issue by kevinavery** [rudderlabs/rudder-server#459]
Hi, it looks like the client IP address in my destinations (Amplitude and Snowflake) matches the IP of the rudder-server node rather than the actual client.

Tested with the latest version [here](https://hub.docker.com/layers/rudderlabs/rudder-server/latest/images/sha256-da61b8533bf5ff0dc0969fdcde261d9dbf03210d7cc7415cc03509d13dd8a20d?context=explore) deployed via rudderstack-helm. As an aside, is there a way to check the version or git hash of rudder-server instance?

**Comment by sivashanmukh** [comment]
We pick up this value from `X-Forwarded-For` header and if its not there, we pick up `RemoteAddr` (doc: [here](https://golang.org/pkg/net/http/)) from the request.

To get the commit number and other details, you can do this

`curl http://<rudder-node-ip>:8080/version`

Incase you want to dig into code, take a look [here](https://github.com/rudderlabs/rudder-server/blob/master/utils/misc/misc.go#L404)

**Comment by kevinavery** [comment]
Looks like AWS ELBs only send `X-Forwarded-For` if the listener protocol is HTTP/S, but `rudderstack-helm` configures the ELB to use TCP. I'll open an issue there
