### ISSUE TITLE
"High" CPU usage at idle with official Docker setup

### ISSUE THREAD

**Issue by xnyo** [rudderlabs/rudder-server#460]
Hello, I tried setting up rudderstack with docker following the official documentation (https://docs.rudderstack.com/get-started/installing-and-setting-up-rudderstack/docker)
The only change I made to the docker-compose file was changing `WORKSPACE_TOKEN` with the correct value.
The server starts and the events get dispatched correctly, however the CPU usage at idle, with no events whatsoever is about 20-25% on my machine (i7-8550U 3.9GHz). I got similar results on a different machine too. I am running Linux and Docker 19.03.12.
All containers are on the "latest" tag, like in the provided docker-compose file (rudderlabs/rudder-server's hash is `b0cf66d1817c` and rudderlabs/rudder-transformer's hash is `4bb81602b25f`)
Is this normal? If so, is there a way to reduce the CPU usage by tweaking the config file?

Thanks in advance!

**Comment by chandumlg** [comment]
Hi
Sorry for the late response.

Please set the following environment variables. They will bring down the CPU usage drastically.
RSERVER_PROCESSOR_FIXED_LOOP_SLEEP_IN_MS
RSERVER_ROUTER_FIXED_LOOP_SLEEP_IN_MS

You can set their value to, say 2000, for 2 secs sleep.

Thanks.
