### ISSUE TITLE
Amplitude error: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by kevinavery** [rudderlabs/rudder-server#461]
Hi, I have a Java source (using `rudder-sdk-java`) connected to an Amplitude destination, and I'm getting the following error in the destination:

Source ID | Attempt No. | Job State | Error Code | Error Response
-- | -- | -- | -- | --
1fIIb8hISkVlmckcwy54umPI0A0 | 1 | aborted | 400 | { "error": "Cannot read property 'name' of undefined" }

**Comment by arnab-p** [comment]
Thanks @kevinavery for pointing out. Will look into it.
