### ISSUE TITLE
Screen event name missing in destinations

### ISSUE THREAD

**Issue by kevinavery** [rudderlabs/rudder-server#466]
Hi, when I send a `screen` event via the HTTP API, the screen `name` is missing in both Amplitude and Snowflake destinations. 

In Amplitude, the following fields are incorrect:
key | rudder | segment
-- | -- | --
display_name | screenview | Viewed `<name>` Screen
event_type | screenview | Viewed `<name>` Screen
event_properties.name | | `<name>`

In Snowflake, the Name column in the Screens table is null.

**Comment by psrikanth88** [comment]
@kevburnsjr Thanks for pointing out. This has been fixed for warehouse destinations. Please update your transfomer image to version `01082020.093209`

**Comment by kevinavery** [comment]
@psrikanth88 thanks, looks like that fixes the Snowflake issue. Let me know when the Amplitude fix lands. It's likely related to a similar issue I noted here https://github.com/rudderlabs/rudder-sdk-js/issues/79#issuecomment-666785546
