### ISSUE TITLE
Snowflake: Missing userId incorrectly stored as <nil> string

### ISSUE THREAD

**Issue by kevinavery** [rudderlabs/rudder-server#467]
Hi, events with a null `userId` are being stored in Snowflake with the string value `<nil>` rather than the `null` value.

**Comment by psrikanth88** [comment]
@kevburnsjr Thanks for pointing out. This has been fixed. Please update your transfomer image to version `01082020.093209`

**Comment by kevinavery** [comment]
Thanks, looks like this is fixed on my end!
