### ISSUE TITLE
Bugsnag Configuration

### ISSUE THREAD

**Issue by mparaz** [rudderlabs/rudder-server#49]
I think the Bugsnag API Key should be removed from the code and be externalised. 
Should everyone trying the project get their own key?

**Comment by soumyadebm** [comment]
Great point. We will submit a pull request soon

**Comment by soumyadebm** [comment]
Thanks Miguel for submitting the pull request. Will approve once the team checks the CI/CD pipeline. 

Welcome to the Rudder community :) Would appreciate if you join or discord channel  too - https://discordapp.com/channels/625629179697692673/
