### ISSUE TITLE
Compatibility with CockroachDB

### ISSUE THREAD

**Issue by ramkumarkb** [rudderlabs/rudder-server#494]
This is a duplicate of the closed issue #163 

Nevertheless, I tried to run `rudder-server` with CockroachDB today but got an error - 

```
ERROR   Rudder server needs postgres version >= 10. Exiting.
```

Understand from the CockroachDB docs that it is compatible with Postgres `v9.5` onwards - 
https://www.cockroachlabs.com/docs/v20.1/postgresql-compatibility.html  

Does rudder-server use postgres specific features like store-procs, functions or triggers? (If not, it would be nice to have the scale-out features of CRDB for the backend).

**Comment by snarkychef** [comment]
Yes, we use triggers.
