### ISSUE TITLE
Maybe we release a wrong image?

### ISSUE THREAD

**Issue by weijiany** [rudderlabs/rudder-server#5026]
**Describe the bug**

Today(2024-08-26), renovate would update rudderlabs/rudder-server image, we found that the version is [31082021.130106](https://hub.docker.com/layers/rudderlabs/rudder-server/31082021.130106/images/sha256-79a922041bd90c6672e597235a4c0d9da3a186d7378f16b0b047f0214b1546f3?context=explore), I guess our release workflow maybe have an issue?

Maybe this is our expectation?

🤔 🤔 🤔

**Comment by gitcommitshow** [comment]
`rudderlabs/rudder-server` is the correct image. Which tag are you using to install?

**Comment by weijiany** [comment]
Hi @gitcommitshow thanks for you reply, I found the latest tag is [31082021.130106](https://hub.docker.com/layers/rudderlabs/rudder-server/31082021.130106/images/sha256-79a922041bd90c6672e597235a4c0d9da3a186d7378f16b0b047f0214b1546f3?context=explore), I'm not sure is it correct?

**Comment by gitcommitshow** [comment]
That seems to be a quite old version. Download from the latets tag instead i.e. [`rudderlabs/rudder-server:latest`](https://hub.docker.com/layers/rudderlabs/rudder-server/latest/images/sha256-e74a177d14f857cd6d7c12b2a875e468d0de4d104d8317f356b8c426ee790b92)

**Comment by weijiany** [comment]
> Hi @gitcommitshow thanks for you reply, I found the latest tag is [31082021.130106](https://hub.docker.com/layers/rudderlabs/rudder-server/31082021.130106/images/sha256-79a922041bd90c6672e597235a4c0d9da3a186d7378f16b0b047f0214b1546f3?context=explore), I'm not sure is it correct?

Sorry not the latest tag, that is the maximal major version tag is.

> That seems to be a quite old version. Download using the latest tag instead i.e. [rudderlabs/rudder-server:latest](https://hub.docker.com/layers/rudderlabs/rudder-server/latest/images/sha256-e74a177d14f857cd6d7c12b2a875e468d0de4d104d8317f356b8c426ee790b92)

I prefer not to use the "latest" tag, as it might introduce breaking changes that could cause issues for our business. Therefore, I always opt for a specific version.

This week, I integrated a dependency manager (Renovate) for the rudder-server. Renovate attempted to update the rudder-server image to the 31082021.130106 tag, which turned out to be an error for me. I would like to know if there are plans to remove this unusual tag.

**Comment by gitcommitshow** [comment]
I'm not familiar with renovate but if you want to install the latest stable release that is `1.32` which can be installed by `docker pull rudderlabs/rudder-server:1.32`

You can check the latest release versions in the GitHub Releases section of this repo.
