### ISSUE TITLE
High CPU usage for low traffic website. 

### ISSUE THREAD

**Issue by Sshuichi** [rudderlabs/rudder-server#503]
Hi, this is my server configuration: 
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Xeon(R) CPU E3-1275 v6 @ 3.80GHz
Stepping:                        9
CPU MHz:                         4076.275
CPU max MHz:                     4200.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7599.80
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
```

I have 20 req/sec on average 
The load without Rudderstack: 
`0.21 0.23 0.26`
With Rudderstack 
`1.41 1.36 1.56`

**Comment by SumanthPuram** [comment]
Hi @Sshuichi 
We fixed this as part of this [PR](https://github.com/rudderlabs/rudder-server/pull/698).

**Comment by Sshuichi** [comment]
Thank you so much. 
Is it available for upgrade on the docket image?

**Comment by Sshuichi** [comment]
Thanks @SumanthPuram how does this fix the issue? Can we configure the sleep timer?

**Comment by SumanthPuram** [comment]
We don't have nightly builds yet. We will release an image this week.

You need to configure an environment variable for sleep. @Sshuichi

**Comment by Sshuichi** [comment]
Thanks! please let us know when the image is released.

**Comment by Sshuichi** [comment]
Hello, was the image released? Also what is the variable to adjust when pulling the new image?

**Comment by chandumlg** [comment]
Hi
Sorry for the late response, you can use any of the latest images.

Please use the following environment variables to configure the sleep timer.
RSERVER_PROCESSOR_FIXED_LOOP_SLEEP_IN_MS
RSERVER_ROUTER_FIXED_LOOP_SLEEP_IN_MS 

You can set their value to, say 2000, for 2 secs sleep.

Thanks.
