### ISSUE TITLE
Terraform support for Google Cloud

### ISSUE THREAD

**Issue by SumanthPuram** [rudderlabs/rudder-server#53]
We have Terraform scripts to deploy rudder-server and it's dependencies (i.e., PostgreSQL, transformer) in AWS in the repo https://github.com/rudderlabs/rudder-terraform

We would need help to set up on GoogleCloud.

**Comment by GaryPWhite** [comment]
@SumanthPuram hmmm -- is this perhaps something we could use an account for? I've worked with GCS in helping to build `bbl` https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/getting-started-gcp.md and played with terraform as a result, I'd love to sink my teeth in and get this working but do not have the budget :)
