### ISSUE TITLE
postgres namespace field dissapeared

### ISSUE THREAD

**Issue by aviam** [rudderlabs/rudder-server#534]
Hello ,

I'm using a hosted data plane,  from Postgres configuration, current and new one namespace field is not appear anymore.
from 1/9 my sources ( js and react native) write to different namespaces in my Postgres destination although it was configured to write to the namespace defined in the Postgres configuration form.

So now all my queries based on this destination are corrupted.
Please fix ASAP

**Comment by gane5hvarma** [comment]
fixed it. you should be able to see data in your namespace
