### ISSUE TITLE
Can no longer access `event.properties` in user transforms

### ISSUE THREAD

**Issue by pierreavizou** [rudderlabs/rudder-server#535]
After updating to the latest version of the docker image (as of Sept 08 2020), it looks like events sent to user transform functions no longer have the `properties` key. 

This is the case at least for page events. 

So in a user transform function like
```js
function transform(events) {
  return events.map(e => {
  // Process events
  })
}
 ```

`e.properties` is undefined. 

With a previous version of Rudder Server, it was working fine. 

So for instance if I want to access the `title` property of a page event, I can no longer write `e.properties.title`. 
As a workaround, I found that using `e.context.page.title` was working, but that does not seem to be the documented / recommended way of doing it.

**Comment by cisse21** [comment]
for recommended usuage / better working experience …..
use v1 version of transformation

https://github.com/rudderlabs/sample-user-transformers
