### ISSUE TITLE
Terraform support for Azure

### ISSUE THREAD

**Issue by SumanthPuram** [rudderlabs/rudder-server#54]
We have Terraform scripts to deploy rudder-server and it's dependencies (i.e., PostgreSQL, transformer) in AWS in the repo https://github.com/rudderlabs/rudder-terraform

We would need help to set up on Azure.

**Comment by SumanthPuram** [comment]
We have Terraform scripts to deploy rudder-server and it's dependencies (i.e., PostgreSQL, transformer) in AWS in the repo https://github.com/rudderlabs/rudder-terraform

We would need help to set up on Azure.

**Comment by GaryPWhite** [comment]
Same question I had for Google Cloud, but for Azure. Don't want to spend a bunch of money building the PR! Am somewhat familiar with terraform/azure but moreso with GCP, let me know!
