### ISSUE TITLE
OnChange notifiers for backend config

### ISSUE THREAD

**Issue by SumanthPuram** [rudderlabs/rudder-server#55]
Right now, backend polls the config-backend every n secs and forwards the latest config to all subscribers (eg. router, processor). We would eventually want to move to sockets to handle the changes instead of polling.

backend-config module should only notify changes to subscribers. It should also expose an API to return the complete config. This API would help subscribers who are coming online for the first time or if it missed handling some changes.

**Comment by diptag** [comment]
I would like to take this up.

**Comment by SumanthPuram** [comment]
Thanks @diptag 

- config/backend-config/backend-config.go

This file fetches the config from the backend and publishes it on an event bus.
```
Eb.Publish("backendconfig", sourceJSON)
```

The backend config is not a frequently changed value. All the subscribers need not know about every fetch.

backend-config.go should have a local copy and only notify the subscribers when things change.
It should also export a function that would give the latest state of the config. If the subscriber joins after the server starts, it needs to get the latest config once and then subscribe for changes.

Let me know if you have any questions. Would be glad to help you.
