### ISSUE TITLE
Add support for MinIO file destination 

### ISSUE THREAD

**Issue by SumanthPuram** [rudderlabs/rudder-server#56]
Currently, we support S3 as a destination for events. We should extend the support MinIO.

**Comment by SumanthPuram** [comment]
Currently, we support S3 as a destination for events. We should extend the support MinIO

**Comment by obukhov** [comment]
I would like to work on that one

**Comment by SumanthPuram** [comment]
Thanks @obukhov 

We have fileuploader package under the services folder. We want to clean this up a bit more in future - Have FileManager abstraction (instead of FileUploader alone), that supports downloads as well.

**Comment by obukhov** [comment]
Sorry I was investigating the code a bit and made some research implementation (to study minio sdk): https://github.com/obukhov/rudder-server/tree/minio-fileuploader

I found 3 different cases of uploading the files:
- jobsdb/jobsdb.go:1407
- jobsdb/jobsdb.go:1409
- router/batchrouter/batchrouter.go:95

I was thinking if all these cases should be configured with the single configuration (all either minio or aws-s3) or should they be configured separately.

I think I've understood now how data flows inside the application and how to run it with local configuration server.

Can you explain a bit what do you mean by FileManager abstraction? What are the other cases to use it compared to FileUploader?

**Comment by SumanthPuram** [comment]
Great to know that you understood the flows.

Dumping PostgreSQL tables to Files before deleting
- jobsdb/jobsdb.go:1407
- jobsdb/jobsdb.go:1409

S3 as destination
- router/batchrouter/batchrouter.go

So both the configurations would be different.

FileManager would include both FileUploader and FileDownloader. We don't have a FileDownloader now. Not an immediate requirement though.

**Comment by obukhov** [comment]
I was just looking at backup of the tables, and have a question regarding that:
```
pathPrefix := strings.TrimPrefix(tableName, "pre_drop_")
	path := fmt.Sprintf(`%v%v.json`, config.GetEnv("TMPDIR", "/home/ubuntu/s3/"), pathPrefix)
	copyStmt := fmt.Sprintf(`COPY (SELECT row_to_json(%v) FROM (SELECT * FROM %v) %v) TO '%v';`, dbname, tableName, dbname, path)
	_, err = jd.dbHandle.Exec(copyStmt)
	jd.assertError(err)

	zipFilePath := fmt.Sprintf(`%v.zip`, path)
	err = misc.ZipFiles(zipFilePath, []string{path})
	jd.assertError(err)
```
Does that assume that ruddler-server binary runs on the same host as postgresdb? Because I am runnig in in dockerized environment and it is not true (as it doesn't have shared volumes) between these two containers.

**Comment by SumanthPuram** [comment]
That's a great observation. Yes, you got it right. Right now, the server runs in the same machine as the postgresdb. During our development on Docker, we disable backups to files.

We need to remove that restriction and be able to run Postgres on any machine. That is in our pipeline. I will create a separate issue for the same. You can have a look if you would like to.

**Comment by SumanthPuram** [comment]
Create a new issue for dumping files. 
https://github.com/rudderlabs/rudder-server/issues/63

**Comment by obukhov** [comment]
I solved that problem for local development by mounting host machine folder, and was able to test backup uploads to minio (it is not creating buckets automatically though). Do you think it should?

Regarding using minio bucket as a destination, I think I should somehow create configuration for this type of destination in configuration backend. As far as I understood configuration backend is a private repo? Do you have any advice on how to simulate that?

**Comment by SumanthPuram** [comment]
We expect users to create the bucket and ask them for s3:PutObject permissions on a given bucket to dump the files. The ability to create the bucket is added flexibility, but we can do that if users want it. We would like to keep permissions to minimal.  

Regarding the config-backend, we are planning to open-source it soon. 
What all parameters do we need to ask for MinIO destination? Server URL, bucket name etc. If you can give me the list of parameters, I will enable the destination.

**Comment by obukhov** [comment]
@SumanthPuram well if we follow s3 example - it is just "bucketname", all credentials are provided through env variables for s3. But if we are talking about full data (to support multiple instances as destinations), then it is also:
- MINIO_ENDPOINT
- MINIO_ACCESS_KEY_ID
- MINIO_SECRET_ACCESS_KEY
- MINIO_USE_SSL

**Comment by SumanthPuram** [comment]
S3 as a destination needs more documentation to enable the rudder-server to be able to write into destination buckets. Don't think it is a standard in the AWS world to share ACCESS_KEY_ID and SECRET_ACCESS_KEY.  So we will ask the user to create a policy that enables us to be able to write to their buckets.

For now, please assume that the following would be available to you per destination. We will add that in backend config and propagate it MinIO destination router.

- MINIO_ENDPOINT
- MINIO_ACCESS_KEY_ID
- MINIO_SECRET_ACCESS_KEY
- MINIO_USE_SSL

**Comment by obukhov** [comment]
@SumanthPuram my implementation is ready. Unfortunately wasn't able to test it completely, but at least it builds. If you can send me a binary (or docker image link) of config server supporting minio destination, as discussed, I can also test it.

**Comment by SumanthPuram** [comment]
I just reviewed and it looks great @obukhov.
I will send you a docker image today with MinIO enabled. I also created another issue for testing this. If you like to work it, you can take it up. I am also marking it as help wanted.

https://github.com/rudderlabs/rudder-server/issues/67

**Comment by SumanthPuram** [comment]
@obukhov We added MinIO destination with 4 parameters as you mentioned. Please check out app.rudderlabs.com. 

Thanks @lokey for adding the destination support.

**Comment by obukhov** [comment]
@SumanthPuram thanks! I'll test it

**Comment by SumanthPuram** [comment]
@obukhov Can you please merge the latest master and check? It has fixed the database dependency, now DB can run on a different machine. 
We also changed fileUploader to filemanager. There were quite a few stability fixes and new features that went in the last 3 weeks.

If you want, I can fork your branch and merge the master and put a PR back to your repo. We can then merge your repo into the master.
