### ISSUE TITLE
docker images tags do not correspond with releases

### ISSUE THREAD

**Issue by jalberto** [rudderlabs/rudder-server#569]
will be very useful if docker image tags use the same version system as the release in Github

**Comment by jalberto** [comment]
Lates tag is from 7mo ago

![image](https://user-images.githubusercontent.com/99927/96117910-12c5fa00-0eeb-11eb-8eeb-25d058707a21.png)

while lates stable 0.1.9 release is from 20 Jun

**Comment by yanivyalda** [comment]
agreed it's confusing. We don't know which version to use as well.

**Comment by marcossv9** [comment]
+1 to this. Another good option could be to add a **stable** docker image also. Every one-two days there is a new docker-image.. It is not good practice..

**Comment by jalberto** [comment]
@marcossv9 a fixed tag will bring the same issues, the ideal solution is to have a new tag for each release, but that tag needs to be in sync with the repo.

My perception is rudder lads are not too motivated to make the self-hosted option easier to use.

**Comment by SumanthPuram** [comment]
@jalberto @marcossv9 @yanivyalda 
Apologies for the delayed response. We did chat internally and wanted to get your feedback. The following PR is our plan towards managing the release tags in docker and deprecating Github releases. 

Please let us know your feedback on this.


https://github.com/rudderlabs/rudder-server/pull/999

**Comment by chandumlg** [comment]
We now follow semver and docker tags are same as the releases.
