### ISSUE TITLE
Jamstack instrumentation - Gatsby plugin + Netlify function

### ISSUE THREAD

**Issue by thtmnisamnstr** [rudderlabs/rudder-server#655]
# GitHub Sponsors Bounty
**Bounty Amount:**  $2,000

**\*\*\* DO NOT SUBMIT A PULL REQUEST FOR ANY BUG OR ENHANCEMENT WITH AN ASSOCIATED BOUNTY UNLESS IT IS ASSIGNED TO YOU. PULL REQUESTS FROM UNASSIGNED CONTRIBUTORS WILL BE REJECTED. \*\*\***

## How Bounties Work
* Apply to work on this via the Google Form [here](https://forms.gle/Qifc1xF6Db3uBD7A8). You can apply as an individual or as a team.
  * Provide the issue number, a link to the issue, GitHub usernames for you and all team members, a single contact email, an estimated date that you think you could complete work by, and a brief note on why we should select you/your team.
  * **You and everybody on your team must have GitHub Sponsors enabled.** Details on how to enable GitHub Sponsors on your account are [here](https://docs.github.com/en/free-pro-team@latest/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account). If you are on the GitHub Sponsors waitlist and are selected, we will work with GitHub to get you approved quickly.
* If we are interested in your application, we will reach out via email. If we aren't, we will do our best to reach out in some way as well.
* Once a contributor is selected, they will be assigned the Issue in GitHub, and applications will be closed.
* After completion and a PR has been approved (not necessarily merged) by RudderStack, the contributor will be paid via GitHub sponsors in the most expedient way possible (e.g. until one-time payments are implemented for GitHub Sponsors, if bounty = $2500 => 2-months of $1000 sponsorship and 1-month of $500 sponsorship).

# Enhancement Info
## Description
Jamstack is gaining momentum rapidly. The technology is maturing and more people are experimenting with it. 

Something that is currently missing or it’s difficult to implement is event capturing on a Jamstack website. It can be done, but adding something like RudderStack makes a ton of sense for Jamstack for a couple of reasons.
1. You want to reduce the lib payload as much as possible. By using, one library instead of a couple, will make a big difference and that’s important for a technology stack that has speed and latency as one of the main value drivers.
2. You want to reduce the number of deployments. By incorporating something like RudderStack, the developer can add one library and make add more apps that will receive the events on the backend without redeploying.

Another reason is that by using RudderStack together with a Function on Netlify, we can proxy the analytics calls and thus avoid issues with calls to third party domains.

For this implementation we want to support one of the most common Jamstack setups, which is the combination of Gatsby and Netlify.

## Implementation
The first part of the implementation is a _plugin_ for [Gatsby](https://www.gatsbyjs.com/). The plugin can be similar to the Segment plugin that can be found [here](https://www.gatsbyjs.com/plugins/gatsby-plugin-segment-js/). The implementation is quite straightforward and includes:
1. A way to track custom events from within a Gatsby project.
2. A way to automatically catch page views and send them to RudderStack.

In addition to the above, we want to also create a [Netlify Function](https://docs.netlify.com/functions/overview/) that can be used as a way to Proxy the tracked events through that. 

For an example of how this can be done, please refer to [this project](https://github.com/google/eleventy-high-performance-blog) and more specifically on how GA is being handled. More specifically check the implementation [here](https://github.com/google/eleventy-high-performance-blog/blob/main/functions/ga.js).

_The implementation of event capturing should avoid blocking onload on analytics requests._

## Nice to have features
1. It would be great if the project could support more than Netlify as a proxy.
2. It would be awesome if the Gatsby plugin could create a “schema” of the events that are being tracked across the project.

**Comment by cwray-tech** [comment]
Starting work on this today! Excited! Thank you for the opportunity.

**Comment by cwray-tech** [comment]
@mister-josuecedeno This is the main GitHub Issue.

**Comment by cwray-tech** [comment]
@mister-josuecedeno Here is another bounty project that Rudderstack has going on: https://dev.to/rudderstack/rudderstack-feature-bounty-shopify-app-2-000-3kba

**Comment by thtmnisamnstr** [comment]
https://github.com/rudderlabs/gatsby-plugin-rudderstack
