### ISSUE TITLE
Roku SDK

### ISSUE THREAD

**Issue by thtmnisamnstr** [rudderlabs/rudder-server#656]
# GitHub Sponsors Bounty
**Bounty Amount:**  $2,000

**\*\*\* DO NOT SUBMIT A PULL REQUEST FOR ANY BUG OR ENHANCEMENT WITH AN ASSOCIATED BOUNTY UNLESS IT IS ASSIGNED TO YOU. PULL REQUESTS FROM UNASSIGNED CONTRIBUTORS WILL BE REJECTED. \*\*\***

## How Bounties Work
* Apply to work on this via the Google Form [here](https://forms.gle/Qifc1xF6Db3uBD7A8). You can apply as an individual or as a team.
  * Provide the issue number, a link to the issue, GitHub usernames for you and all team members, a single contact email, an estimated date that you think you could complete work by, and a brief note on why we should select you/your team.
  * **You and everybody on your team must have GitHub Sponsors enabled.** Details on how to enable GitHub Sponsors on your account are [here](https://docs.github.com/en/free-pro-team@latest/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account). If you are on the GitHub Sponsors waitlist and are selected, we will work with GitHub to get you approved quickly.
* If we are interested in your application, we will reach out via email. If we aren't, we will do our best to reach out in some way as well.
* Once a contributor is selected, they will be assigned the Issue in GitHub, and applications will be closed.
* After completion and a PR has been approved (not necessarily merged) by RudderStack, the contributor will be paid via GitHub sponsors in the most expedient way possible (e.g. until one-time payments are implemented for GitHub Sponsors, if bounty = $2500 => 2-months of $1000 sponsorship and 1-month of $500 sponsorship).

# Enhancement Info
## Description
Roku is one of the largest OTT device platforms by distribution. That means there are a ton of people using Roku. But there isn’t a good way to track customer events from Roku applications and unify that data with the rest of your customer data. So you can’t really know how usage in your Roku app impacts customer behavior, or, if you can, you had to do a lot of work to get there.

We want to make it easier to collect and use customer data from Roku with this implementation.

## Implementation
This implementation will be in a new repo under RudderStack’s GitHub organization. The SDK can be similar to the Segment implementation found [here](https://github.com/segmentio/analytics-roku). The SDK needs to implement:
1. A way to automatically catch actions in a Roku application and send them to RudderStack as events.
2. A way to track custom events from within a Roku application.
Another example of Roku instrumentation is from New Relic [here](https://github.com/newrelic/video-agent-roku). It may be worthwhile to review their implementation in addition to Segment’s.

## Nice to have features
1. It would be great if the SDK’s implemented as much of our JavaScript SDK [here](https://github.com/rudderlabs/rudder-sdk-js) as is reasonable.

**Comment by 0-sv** [comment]
Is this bounty still open?

**Comment by gitcommitshow** [comment]
@0-sv this issue is quite old. We do not have any issue bounty at the moment. Having said that 

* If you want to contribute any integration(such as Roku), here's the guide on how to [develop new integrations for RudderStack](https://www.rudderstack.com/docs/user-guides/how-to-guides/developing-integrations-for-rudderstack/)
* We have an ongoing R[udderStack Transformations challenge](https://www.rudderstack.com/blog/join-the-transformations-challenge-for-a-chance-to-win/) which has rewards ranging from $100-$1000. Do check that out.
