### ISSUE TITLE
I see a need to simplify configuration for open source.

### ISSUE THREAD

**Issue by irafikh** [rudderlabs/rudder-server#667]
There are several possible ways:
- to add config file export from cloud GUI
- to create docker with config gen
- to publish config file definition.

Free tier not allows to check queues performance and not only, paid tiers before enterprise level not allows to use own network.

When some component as config-gen too sensitive to to OS and dependencies + config file is not defined, unfortunately, this not helps you to find new fans ((...

**Comment by gitcommitshow** [comment]
This seems to be an old issue but it is always a good reminder to think about this point.
Let's brainstorm this in discussions page and see if we can get some concrete actions out of this  - https://github.com/rudderlabs/rudder-server/discussions/2260
