### ISSUE TITLE
Create a test that verifies MinIO/S3 destination is working

### ISSUE THREAD

**Issue by SumanthPuram** [rudderlabs/rudder-server#67]
We are using GinkGo for integration tests. 
Right now, we have different test suites for the following:
1. Events are being sent to router tables after all the required transformations
2. Uploading of event schema to config-backend is working as expected
3. Tables are being migrated/deleted/backed up after successful completion.

We need to add a test to see if MinIO destination is working as expected.

**Comment by SanketDG** [comment]
I am interested in taking this up.

Where exactly would this test reside?
