### ISSUE TITLE
Bug with Webhook destination: Invalid memory address

### ISSUE THREAD

**Issue by mfrye-blue-owl** [rudderlabs/rudder-server#680]
I have the default setup and I'm trying to test a Webook destination, but I'm running into an error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x1f320a1]

goroutine 170 [running]:
github.com/rudderlabs/rudder-server/router.(*NetHandleT).Setup(0xc000250480, 0xc000324ca0, 0x7, 0x6fc23ac00)
	/Users/michael/go/github.com/rudderlabs/rudder-server/router/network.go:163 +0x361
github.com/rudderlabs/rudder-server/router.(*HandleT).Setup(0xc000421380, 0xc00000c5a0, 0xc000324ca0, 0x7)
	/Users/michael/go/github.com/rudderlabs/rudder-server/router/router.go:926 +0x3e1
main.monitorDestRouters(0xc00000c5a0, 0xc00000c780)
	/Users/michael/go/github.com/rudderlabs/rudder-server/main.go:123 +0x76e
created by main.StartRouter
	/Users/michael/go/github.com/rudderlabs/rudder-server/main.go:233 +0xc3
exit status 2
```

I'm running `go version go1.14.1 darwin/amd64`.

Some of the line numbers above are likely a little off as I'm trying to debug and my go is a bit rusty. It seems to be blowing up on this line though:
```
network.logger.Info(destID, defaultTransportCopy.TLSClientConfig.NextProtos)
```

**Comment by rsaphala** [comment]
getting this error as well. any updates on this?

**Comment by SumanthPuram** [comment]
This has been fixed.

**Comment by mfrye-blue-owl** [comment]
@SumanthPuram thanks for fixing this. 

Just a heads up though, our company was seriously exploring RudderStack at the time I opened this. Based on the lack of response on this bug and general challenges on getting setup, we decided not to proceed. 

Frankly, this seems like it could be a great project and touches on a major problem, but it's all about the execution.

**Comment by SumanthPuram** [comment]
@mfrye-blue-owl We fixed this a couple of days after this issue showed up in our deployments.

We are working on our release process for stabler open source builds.

My bad, we didn't actively follow up on GitHub. Our team is active on the Slack community.

Thanks for the feedback, we will discuss with the team and improve the process going forward.
