### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by Ruth-ikegah** [rudderlabs/rudder-server#705]
**Description:** There is no issue template so when someone wants to create an issue there is no section and it can be limiting to properly explain the issue 

**Desired Behaviour:** Create different sections of issues like a bug report, feature request, and questions. Then populate each section to serve as a template for anyone creating an issue.
An example of the content for a bug report:

**Description**

**Expected Behavior**

**Screenshots**

**Comment by chandumlg** [comment]
We now have a Bug Report issue template.
