### ISSUE TITLE
dial udp: address <stat_server_url>: missing port in address

### ISSUE THREAD

**Issue by akbansa** [rudderlabs/rudder-server#743]
While doing setup for the server and running the last command `./rudder-server`, it gives **`dial udp: address <stat_server_url>: missing port in address`** error.

As per discussion over the slack, `statsd` is not required for the Rudderstack to function. So some config level changes can be done to avoid this error and those who want to use this can enable it from the config.

@gane5hvarma This will help reduce queries related to this error.

**Comment by chandumlg** [comment]
@akbansa You can turn off stats(to avoid seeing these errors) using this config variable.
https://github.com/rudderlabs/rudder-server/blob/8b3db7d9466c099a754a1465c97091daec9b62a9/config/config.yaml#L6
