### ISSUE TITLE
Once again, please stop spamming people

### ISSUE THREAD

**Issue by dd32** [rudderlabs/rudder-server#756]
As a follow up to #532 #526

Please stop harvesting email addresses of GitHub contributors, it's poor practice and while I'd usually just ignore it, you've been asked to stop it before.. so once again, please stop it.

Just because someone has stared or forked a "related repo" it doesn't mean we're interested.

```
From: Soumyadeb Mitra <mitra@rudderlabs.com>
Date: Mon, 4 Jan 2021 20:44:57 -0800
Subject: GitHub Outreach - Looking for Feedback
To: ....email from a git commit log, not my public GitHub profile email....

Hi,

Hope you are well. I came across your GitHub profile while browsing.

My team and I are building an open source project/company called
RudderStack. In a nutshell, it's an open source alternative to Segment
built specifically for developers ( https://github.com/rudderlabs/rudder-server/).

As we are a young open source project, we are trying to engage with active
and experienced developers like you to receive suggestions, contributions,
and of course criticism (the best kind of feedback [image: =F0=9F=98=81]).

Here's our Github Repository
<tracking link to this github repo>.
Stars, forks, Issues and pull requests are more than welcome and highly
appreciated.

Thank you so much for your time!

Soumyadeb

P.S. You can also check HackerNews <tracking link>
for some more information about the project.

Virus-free.
www.avast.com
```

**Comment by daviddarnes** [comment]
Received the exact same email this morning. I thought I'd check the issues incase something like this had been reported, I'm kinda surprised it has been! Clearly this is a major issue, it's been reported 3 times without resolution (#756, #532, #526).
Please stop spamming people and please stop asking for free help on your premium platform.

**Comment by soumyadebm** [comment]
We have received very good feedback too from the community and hence we continued doing it. Will be careful on whom we reach out going forward
