### ISSUE TITLE
DeepSource raises zero issues

### ISSUE THREAD

**Issue by sourya-deepsource** [rudderlabs/rudder-server#775]
A recent commit added a `.deepsource.toml`, with JavaScript and Go analyzers enabled. However, Go checks are not running, and JavaScript analysis returns zero issues.

This is an issue with the TOML configuration that has been added:
1. `dependencies_vendored` is a boolean. A recent bug in DeepSource configuration generator resulted in setting it to a string value. (This bug has been fixed now).
2. JavaScript analyzer needs some more information, like the framework being used and the use of typescript.

A change in configuration will fix this issue.

**Comment by sivashanmukh** [comment]
This has been merged and we are actively tracking the issues on deepsource.
