### ISSUE TITLE
Batch timeout logic is incorrect

### ISSUE THREAD

**Issue by kevburnsjr** [rudderlabs/rudder-server#78]
Batch timeout logic measures time between **events** rather than time between **batches**.

As a result, the default configuration of `maxBatchSize=32` and `batchTimeout=20ms` can add up to **600ms of latency** to a request. 

Example: https://play.golang.org/p/nKCpiwIMxFs

See `gateway.webRequestBatcher`:

https://github.com/rudderlabs/rudder-server/blob/995e9ca26a05e301b0b4fb7bf3665829c3cb0a2e/gateway/gateway.go#L246

**Comment by SumanthPuram** [comment]
Thanks @kevburnsjr for pointing this. We have fixed it now.

**Comment by kevburnsjr** [comment]
Close.

You should instead restart the timeout after each time the batch is done sending (rather than begins sending) and then you should be good.

```go
//Function to batch incoming web requests
func (gateway *HandleT) webRequestBatcher() {
	var reqBuffer = make([]*webRequestT, 0)
	timeout := time.After(batchTimeout)
	for {
		select {
		case req := <-gateway.webRequestQ:
			//Append to request buffer
			reqBuffer = append(reqBuffer, req)
			if len(reqBuffer) == maxBatchSize {
				breq := batchWebRequestT{batchRequest: reqBuffer}
				gateway.batchRequestQ <- &breq
				reqBuffer = nil
				reqBuffer = make([]*webRequestT, 0)
				timeout = time.After(batchTimeout)         // <------- Here
			}
		case <-timeout:
			if len(reqBuffer) > 0 {
				breq := batchWebRequestT{batchRequest: reqBuffer}
				gateway.batchRequestQ <- &breq
				reqBuffer = nil
				reqBuffer = make([]*webRequestT, 0)
				timeout = time.After(batchTimeout)         // <------- Here
			}
		}
	}
}
```
