### ISSUE TITLE
Gateway never returns 500

### ISSUE THREAD

**Issue by kevburnsjr** [rudderlabs/rudder-server#79]
API Requests to rudder-server will only ever return a status code of 200 or 400.

https://github.com/rudderlabs/rudder-server/blob/995e9ca26a05e301b0b4fb7bf3665829c3cb0a2e/gateway/gateway.go#L323-L329

This is problematic for at least 2 reasons

### 1) Lack of differentiation between 400 and 500 reduces visibility into service operation.

Services should differentiate between client errors and server errors. If the database becomes unavailable, you want the service to return 500 so that your alerting system can page the OPS team.

### 2) Clients treat 4xx and 5xx differently

Some clients will **retry** events when they receive a 500 and **remove** events when they receive a 400.

https://github.com/segmentio/analytics-android/blob/47f7341d81766b1b4a101ef69f491835d11f7532/analytics/src/main/java/com/segment/analytics/SegmentIntegration.java#L386-L394

The service must return 5xx on server error in order to minimize event loss during service outage.

**Comment by chandumlg** [comment]
Gateway error codes are corrected.
