### ISSUE TITLE
Shopify app

### ISSUE THREAD

**Issue by thtmnisamnstr** [rudderlabs/rudder-server#793]
# GitHub Sponsors Bounty
**Bounty Amount:**  $2,000

**\*\*\* DO NOT SUBMIT A PULL REQUEST FOR ANY BUG OR ENHANCEMENT WITH AN ASSOCIATED BOUNTY UNLESS IT IS ASSIGNED TO YOU. PULL REQUESTS FROM UNASSIGNED CONTRIBUTORS WILL BE REJECTED. \*\*\***

## How Bounties Work
* Apply to work on this via the Google Form [here](https://forms.gle/Qifc1xF6Db3uBD7A8). You can apply as an individual or as a team.
  * Provide the issue number, a link to the issue, GitHub usernames for you and all team members, a single contact email, an estimated date that you think you could complete work by, and a brief note on why we should select you/your team.
  * **You and everybody on your team must have GitHub Sponsors enabled.** Details on how to enable GitHub Sponsors on your account are [here](https://docs.github.com/en/free-pro-team@latest/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account). If you are on the GitHub Sponsors waitlist and are selected, we will work with GitHub to get you approved quickly.
* If we are interested in your application, we will reach out via email. If we aren't, we will do our best to reach out in some way as well.
* Once a contributor is selected, they will be assigned the Issue in GitHub, and applications will be closed.
* After completion and a PR has been approved (not necessarily merged) by RudderStack, the contributor will be paid via GitHub sponsors in the most expedient way possible (e.g. until one-time payments are implemented for GitHub Sponsors, if bounty = $2500 => 2-months of $1000 sponsorship and 1-month of $500 sponsorship).

# Enhancement Info
## Description
Shopify is a widely used ecommerce platform. It's estimated that Shopify has almost 20% of the ecommerce platform market share. Event capturing in Shopify is difficult and needs to extend beyond standard event tracking to capture some Shopify-specific events. Adding a tool like RudderStack to your Shopify site makes sense for a few reasons:
1. **You want to track customer events.** Event tracking allows you to perform analysis on your customer behavior, helping you can understand site use, identify purchase trends, etc. Using RudderStack enables sending these events to analytics tools like Google Analytics as well to your data warehouse so you can perfrom your own analysis as well.
2. **You want to reduce the lib payload as much as possible.** Using one event capture library, like RudderStack, instead of multiple, tool-specific libraries will make a big difference in the performance of your site, and that’s important for a technology stack that has speed and latency as one of the main value drivers.
3. **You want to reduce the number of deployments.** By incorporating RudderStack, the developer can deploy one library and be enabled to continually add external apps that will receive the events on the backend without redeploying.

## Implementation
The implementation will be a Shopify app. The app can be similar to the Shopify Tracker developed by Littledata that can be found [here](https://github.com/littledata/shopify-tracker), notably the Segment app part of it [here](https://github.com/littledata/shopify-tracker/tree/master/src/segmentTracker). The implementation should include:
1. A way to track custom events from within Shopify.
2. A way to automatically catch page views and send them to RudderStack.
3. Configurable tracking of Shopify events like productClicks and productPageClicks (see Littledata's [shopify-tracker repo](https://github.com/littledata/shopify-tracker) for additional configuration to enable).
4. The app should implement or wrap as much of our JavaScript SDK [here](https://github.com/rudderlabs/rudder-sdk-js) as is possible.
5. The app must comply with the [Shopify app requirements](https://shopify.dev/concepts/app-store/getting-your-app-approved/app-requirements).

## Nice to have features
1. It would be awesome if the app could create a “schema” of the events that are being tracked across the project.

**Comment by rorito** [comment]
+1 - lack of a shopify integration is a blocker for us

**Comment by arnab-p** [comment]
We have released Shopify app - https://www.rudderstack.com/docs/sources/cloud-apps/shopify/
