### ISSUE TITLE
Request: Hubspot Source

### ISSUE THREAD

**Issue by FinnFrotscher** [rudderlabs/rudder-server#909]
Hi,
the main thing keeping me from replacing segment with rudder is the lack of hubspot as a source.
How do you suggest i solve this or should i wait till you added hubspot as a source.
Finn

**Comment by ryanmccrary** [comment]
Hey @FinnFrotscher we do have HubSpot as a source in our commercial offering, as a part of cloud extract (https://docs.rudderstack.com/cloud-extract-sources/hubspot). Would be happy to setup a call and discuss the integration/migration if that would be helpful.
