### ISSUE TITLE
self-hosted docker-compose setup: Token generation Docs unclear

### ISSUE THREAD

**Issue by FinnFrotscher** [rudderlabs/rudder-server#910]
Hi
i am setting up a bi server and want to replace parts of our segment usage with rudder.
there is a place in your docs where the setup logic becomes circular and thus impossible.

https://docs.rudderstack.com/installing-and-setting-up-rudderstack/docker

1. i have to get the token from the dashboard
2. insert token into the docker-compose
3. in order to start the dashboard

How do i get the token if the dashboard where i get the token requires the token?

**Comment by FinnFrotscher** [comment]
also, the (docker compose)[https://raw.githubusercontent.com/rudderlabs/rudder-server/master/rudder-docker.yml] specifies other files that are not documented

```
      - CONFIG_BACKEND_URL=https://api.rudderlabs.com
      - WORKSPACE_TOKEN=<your_workspace_token>
      - CONFIG_PATH=/app/config/config.toml
```
What is the config backend? isnt that what i am trying to build?
shouldn't the config_path be either placed outside the docker-image, ie. require some kind of Volume `./config.toml:/config.toml`?

**Comment by pChondros** [comment]
Documentation for Docker setup has changed: https://www.rudderstack.com/docs/rudderstack-open-source/installing-and-setting-up-rudderstack/docker/. To complete the setup you only need to replace your workspace token that you can obtain from the [RudderStack Open Source dashboard](https://app.rudderstack.com/signup?type=opensource).
